[package]
name = "nexium"
version = "0.1.0"
authors = ["Nexium Team"]
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
thiserror = "1.0.26"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
log = "0.4.14"
env_logger = "0.9.0"
postbus = "0.2.0"
async-trait = "0.1.51"
mailparse = "0.13.6"
