name: Deployment

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: nexium
          POSTGRES_DB: nexium
    steps:
      - uses: actions/checkout@v2

      - name: Build backend image
        run: docker build ./backend --tag backend
        env:
          DATABASE_URL: "postgres://postgres:nexium@postgres/nexium"

      - name: Build frontend image
        run: docker build ./frontend --tag frontend

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push backend image
        run: |
          IMAGE_ID=$(echo "ghcr.io/${{ github.repository_owner }}/backend" | tr '[:upper:]' '[:lower:]')
          VERSION=$(echo "${{ github.sha }}" | cut -c1-7)

          echo "IMAGE_ID=$IMAGE_ID"
          echo "VERSION=$VERSION"

          docker tag backend:latest "$IMAGE_ID:latest"
          docker tag backend:latest "$IMAGE_ID:$VERSION"
          docker push "$IMAGE_ID:latest"
          docker push "$IMAGE_ID:$VERSION"

      - name: Push frontend image
        run: |
          IMAGE_ID=$(echo "ghcr.io/${{ github.repository_owner }}/frontend" | tr '[:upper:]' '[:lower:]')
          VERSION=$(echo "${{ github.sha }}" | cut -c1-7)

          echo "IMAGE_ID=$IMAGE_ID"
          echo "VERSION=$VERSION"

          docker tag frontend:latest "$IMAGE_ID:latest"
          docker tag frontend:latest "$IMAGE_ID:$VERSION"
          docker push "$IMAGE_ID:latest"
          docker push "$IMAGE_ID:$VERSION"
