name: Frontend Compressed Size
on: [pull_request]

jobs:
  frontend-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm -rf frontend/yarn.lock frontend/package-lock.json
      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: "./dist/{js,css,html}"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          clean-script: "clear-cache"
          strip-hash: "\\.[0-9a-z]{8}"
          cwd: "./frontend"
