name: Rust style checks
on: [push]

jobs:
  clippy:
    runs-on: ubuntu-latest
    container: dsluijk/rust-sqlx-node:latest
    defaults:
      run:
        working-directory: ./backend
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: nexium
          POSTGRES_DB: nexium
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Run Sqlx migrations
        run: sqlx migrate run
        env:
          DATABASE_URL: "postgres://postgres:nexium@postgres/nexium"
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: yarn install
      - name: Build frontend
        working-directory: ./frontend
        run: yarn build
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features --manifest-path ./backend/Cargo.toml -- -D warnings
        env:
          DATABASE_URL: "postgres://postgres:nexium@postgres/nexium"
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path ./backend/Cargo.toml -- --check
